### ISSUE TITLE
Java 11: DEFAULT_JAXWSPROVIDER seems wrong

### ISSUE THREAD

**Issue by col-panic** [eclipse-ee4j/jax-ws-api#90] opened 2019-11-07 09:07 UTC
I use Java 11, and `javax.xml.ws.spi.Provider` (2.3.2) wants to resolve `com.sun.xml.internal.ws.spi.ProviderImpl` which is not provided by `com.sun.xml.ws.jaxws-rt` (2.3.2), where this file is called `com.sun.xml.ws.spi.ProviderImpl`.

What is the right combination to use here??

**Comment by col-panic** [comment] 2019-11-07 10:28
Related https://stackoverflow.com/questions/55748392/migration-to-jakarta-classnotfoundexception-com-sun-xml-internal-ws-spi-provid 
Remark to this: I don't see the connection with `com.sun.org.apache.xml.internal.resolver` (is this supposed to map the internal package name to the new name?) - or at least it does not work in an OSGi environment?!

**Comment by lukasj** [comment] 2019-12-16 12:28
How did you set up your classpath/modulepath?

On JDK 8, this is the fallback to the default implementation from the JDK
On JDK 11 with modulepath, the fallback should not be reached as provides from module-info should match
On JDK 11 with classpath, the fallback should not be reached as the provider should be found in META-INF/services

**Comment by Canos** [comment] 2019-12-17 11:50
i'm stuck on this trying to upgrade an application to Java 11.
In my local developer machine works as expected, but in other environments i get a ClassNotFound.

Not being able to solve the issue following the stackoverflow link provided above.

```
javax.xml.ws.WebServiceException: Provider com.sun.xml.internal.ws.spi.ProviderImpl not found
...
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.ws.spi.ProviderImpl
```

**Comment by lukasj** [comment] 2019-12-17 12:06
If it got this far, then it is likely that jaxws-rt jar is not on the classpath nor modulepath. Can you check that jaxws-rt.jar (version 2.3.3-b01 is preferred) is available?

**Comment by rbradburyquint** [comment] 2019-12-17 13:42
com.sun.xml.internal.ws.spi.ProviderImpl is not in 2.3.3-b01, looks like it doesn't have the "internal" package and is just

`com.sun.xml.ws.spi.ProviderImpl`

**Comment by lukasj** [comment] 2019-12-17 14:31
> com.sun.xml.internal.ws.spi.ProviderImpl is not in 2.3.3-b01, looks like it doesn't have the "internal" package and is just
> 
> `com.sun.xml.ws.spi.ProviderImpl`

correct. There is `META-INF/services/javax.xml.ws.spi.Provider` file containing  `com.sun.xml.ws.spi.ProviderImpl` line as well as module-info file saying: `provides javax.xml.ws.spi.Provider with com.sun.xml.ws.spi.ProviderImpl;` How do you think API jar is supposed to find this implementation specific provider, if it is not on classpath (JDK8/11 case) nor module path (JDK11 case)?

**Comment by Canos** [comment] 2019-12-17 14:58
> If it got this far, then it is likely that jaxws-rt jar is not on the classpath nor modulepath. Can you check that jaxws-rt.jar (version 2.3.3-b01 is preferred) is available?

Yes, it's in included in my final artifact and included in the classpath.

Just to double check, the problem is that the system is looking for the **internal** package: 
```
com.sun.xml.**internal**.ws.spi.ProviderImp
```
Since it's working locally but failing in other non-local environments, i guessed was a matter of configuration, but keep stuck

**Comment by lukasj** [comment] 2019-12-17 15:05
it's returning from https://github.com/eclipse-ee4j/jax-ws-api/blob/master/api/src/main/java/javax/xml/ws/spi/FactoryFinder.java#L77

because the code here: https://github.com/eclipse-ee4j/jax-ws-api/blob/master/api/src/main/java/javax/xml/ws/spi/FactoryFinder.java#L59-L75 did not manage to find different implementation sooner. Question is why?

**Comment by Canos** [comment] 2019-12-17 15:39
The exception is not generated in FactoryFinder, is in [ServiceLoaderUtil.java](https://github.com/eclipse-ee4j/jax-ws-api/blob/2b8d497ed062af0cae74d91256e9bbfdc54f4fc6/api/src/main/java/javax/xml/ws/spi/ServiceLoaderUtil.java#L73)

Probably coming from `checkPackageAccess` method.

```
javax.xml.ws.WebServiceException: Provider com.sun.xml.internal.ws.spi.ProviderImpl not found
	at javax.xml.ws.spi.FactoryFinder$1.createException(FactoryFinder.java:31)
	at javax.xml.ws.spi.FactoryFinder$1.createException(FactoryFinder.java:28)
	at javax.xml.ws.spi.ServiceLoaderUtil.newInstance(ServiceLoaderUtil.java:73)
	at javax.xml.ws.spi.FactoryFinder.find(FactoryFinder.java:82)
	at javax.xml.ws.spi.Provider.provider(Provider.java:66)
	at javax.xml.ws.Service.<init>(Service.java:82)

```

**Comment by lukasj** [comment] 2019-12-17 15:47
> ```
> javax.xml.ws.WebServiceException: Provider com.sun.xml.internal.ws.spi.ProviderImpl not found
> 	at javax.xml.ws.spi.FactoryFinder$1.createException(FactoryFinder.java:31)
> 	at javax.xml.ws.spi.FactoryFinder$1.createException(FactoryFinder.java:28)
> 	at javax.xml.ws.spi.ServiceLoaderUtil.newInstance(ServiceLoaderUtil.java:73)
>```
**at javax.xml.ws.spi.FactoryFinder.find(FactoryFinder.java:82)** - if the code got here, then it couldn't find anything else and it is trying to fallback to the class which is (or better used to be)  defined by JDK 8
> ```
>	at javax.xml.ws.spi.Provider.provider(Provider.java:66)
> 	at javax.xml.ws.Service.<init>(Service.java:82)
> ```

**Comment by Canos** [comment] 2019-12-17 15:50
understood, thanks!

**Comment by Canos** [comment] 2019-12-17 16:13
As you say, I'm trying to provide a parameter to override this behaviour but without success:

```
java -jar myjar.jar --com.sun.xml.internal.ws.spi.ProviderImpl=com.sun.xml.ws.spi.ProviderImpl \
    --com.sun.xml.internal.ws.spi.Provider=com.sun.xml.ws.spi.ProviderImpl \
    --javax.xml.ws.spi.Provider=com.sun.xml.ws.spi.ProviderImpl
```

**Comment by lukasj** [comment] 2019-12-20 21:39
the trap you felt into is documented at [the documentation for java command](https://docs.oracle.com/en/java/javase/13/docs/specs/man/java.html)

> -jar jarfile
> Executes a program encapsulated in a JAR file. ... When you use -jar, the specified JAR file is the source of all user classes, and **other class path settings are ignored**.

This means that you have two options to make it work:
1. add Class-Path definition to the manifest file in your jar file
1. run your app using st like `java -cp myjar.jar:other.jar:jaxws-rt.jar my.Main` instead

**Comment by Canos** [comment] 2019-12-20 22:33
Thank you very much Lukas for your patience and attention.  
 
I think i've found a strange behavior in Spring Boot. 
https://github.com/spring-projects/spring-boot/issues/19427
That's the reason I cannot find the classes.

**Comment by col-panic** [comment] 2020-05-06 07:58
> How did you set up your classpath/modulepath?
> 
> On JDK 8, this is the fallback to the default implementation from the JDK
> On JDK 11 with modulepath, the fallback should not be reached as provides from module-info should match
> On JDK 11 with classpath, the fallback should not be reached as the provider should be found in META-INF/services

After quite some time, we are now forced to do the full Java 11 upgrade - problem still the same!

I'm using an OSGI environment, and it seems that `javax.xml.ws.spi.Provider ` in `jakarta.xml.ws-api_2.3.2.jar' is not able to load `com.sun.xml.ws.spi.ProviderImpl` in `com.sun.xml.ws.jaxws-rt_2.3.2.jar` as they are separated by the osgi environment. 

Yet, I can see, that `javax.xml.ws.spi.FactoryFinder` uses `lookupUsingOSGiServiceLoader` which, however, returns null within 
`((Iterable) m.invoke(null, (Object[]) args)).iterator();`

I even included both plugins as a dependency to my osgi plugin, but it seems like the problem is between ws-api and jaxws-rt?!

**Comment by col-panic** [comment] 2020-05-06 08:52
I'm getting a step further - when performing the following steps on my OSGI bundle requiring the functionality

1.  Import package `com.sun.xml.ws.spi` in `MANIFEST.MF`
2. Adding a `javax.xml.ws.spi.Provider` file in `META-INF/services` containing `com.sun.xml.ws.spi.ProviderImpl`
3. Adding `Thread.currentThread().setContextClassLoader(EcallChSmsMessageTransporter.class.getClassLoader());` just before instantiating my WSDL client 

I end up with 

```
java.lang.NoClassDefFoundError: com/sun/org/apache/xml/internal/resolver/CatalogManager
	at com.sun.xml.ws.util.xml.XmlUtil.createDefaultCatalogResolver(XmlUtil.java:296)
	at com.sun.xml.ws.client.WSServiceDelegate.createCatalogResolver(WSServiceDelegate.java:348)
	at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:334)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:292)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:201)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:182)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:178)
	at com.sun.xml.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:89)
	at javax.xml.ws.Service.<init>(Service.java:82)
	at soap.messaging.ecall.ch.ECall.<init>(ECall.java:44)
	at ch.medelexis.messaging.ecall.internal.EcallChSmsMessageTransporter.activate(EcallChSmsMessageTransporter.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by col-panic** [comment] 2020-05-06 09:55
Following this path further leads me into a rabbit hole with a dependency nightmare at the very end.  Importing the following packages now

```
com.sun.org.apache.xml.internal.resolver,
 com.sun.xml.bind.v2;version="2.3.2",
 com.sun.xml.messaging.saaj.soap;version="1.5.1",
 com.sun.xml.stream.buffer;version="1.5.7",
 com.sun.xml.ws.policy;version="2.7.6",
 com.sun.xml.ws.spi,
 javax.jws;version="1.1.1",
 javax.xml.bind;version="2.3.0",
 javax.xml.bind.annotation;version="2.3.0",
 javax.xml.ws;version="2.3.2",
 org.glassfish.gmbal;version="4.0.0"com.sun.org.apache.xml.internal.resolver,
 com.sun.xml.bind.v2;version="2.3.2",
 com.sun.xml.messaging.saaj.soap;version="1.5.1",
 com.sun.xml.stream.buffer;version="1.5.7",
 com.sun.xml.ws.policy;version="2.7.6",
 com.sun.xml.ws.spi,
 javax.jws;version="1.1.1",
 javax.xml.bind;version="2.3.0",
 javax.xml.bind.annotation;version="2.3.0",
 javax.xml.ws;version="2.3.2",
 org.glassfish.gmbal;version="4.0.0"
```

and added a service resolution for `META-INF/services/javax.xml.soap.SAAJMetaFactory` to `com.sun.xml.messaging.saaj.soap.SAAJMetaFactoryImpl` just to finally retrieve a

```
Mai 06, 2020 11:50:40 VORM. [com.sun.xml.ws.assembler.MetroConfigLoader]  init
SCHWERWIEGEND: MASM0010: Unable to unmarshall metro config file from location [ bundleresource://102.fwk1325154865/META-INF/jaxws-tubes-default.xml ]
javax.xml.bind.JAXBException: "com.sun.xml.ws.runtime.config" enthält ObjectFactory.class oder jaxb.index nicht
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:254)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:208)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:166)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:355)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:508)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:465)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:366)
```

can't image having to do this (not working solution) for every bundle that simply wants to use a webservice client ...

**Comment by lukasj** [comment] 2020-05-06 10:31
if one get:
```
java.lang.NoClassDefFoundError: com/sun/org/apache/xml/internal/resolver/CatalogManager
	at com.sun.xml.ws.util.xml.XmlUtil.createDefaultCatalogResolver(XmlUtil.java:296)
```

with 2.3.2 (or recently released 2.3.3) on Java SE 9 or newer then it is the environment which is wrong since it does not support multi-release jars, thus cannot find/load the right class from META-INF/versions folder. In terms of Ant, one needs 1.10.7 or newer. In all other cases starting JVM with `-Djdk.util.jar.enableMultiRelease=force` may help.

that `META-INF/services/javax.xml.soap.SAAJMetaFactory` thing has been solved in latest release through https://github.com/eclipse-ee4j/saaj-api/issues/43 I believe 

for the rest there is https://github.com/eclipse-ee4j/metro-jax-ws/issues/128

**Comment by col-panic** [comment] 2020-05-07 08:34
Concerning `com/sun/org/apache/xml/internal/resolver/CatalogManager`- I resolve it via 

```
<dependency>
<groupId>com.sun.org.apache.xml.internal</groupId>
<artifactId>resolver</artifactId>
<version>20050927</version>
</dependency>
```
which does not seem to be a multi-release jar?! Where should I resolve `CatalogManager` from?

**Comment by lukasj** [comment] 2020-05-07 08:53
@col-panic I have never said that resolver itself is a multi release jar. I have said that it is not needed at all since it is not supposed to be loaded/required by JDK 9+. What I haven’t said, because I believed it was implied, is that it is jaxws-rt.jar what is a multi release jar.

**Comment by Melnorme1984** [comment] 2020-05-18 13:53
Hey folks,

By sheer coincidence, I've been struggling with this same issue myself on a bundle for Apache Karaf over the past week or so.

I ended up repeating all of col-panic's steps, more-or-less.

1) Swapped the thread context classloader while instantiating my service, as described here: https://helpx.adobe.com/il_en/experience-manager/kb/OsgiClassLoading3Party.html

2) Embedded a bunch of dependencies in my bundle:
```
jakarta.xml.ws-api
jaxws-rt
resolver
streambuffer
policy
stax-ex
jakarta.jws-api
jakarta.xml.soap-api
saaj-impl
gmbal
```
I ended up encountering the same "Unable to unmarshall metro config file" error message as col-panic, but after much experimentation I managed to solve it. In retrospect, the solution should have been obvious: I had left the port initialization code out of the classloader `try` block.

This is how my code looks now:

```
private ServerService(URL wsdlURL) {
	super(wsdlURL, new QName("network", "ServerService"));
	String tmp = wsdlURL.toString();
	path = tmp.substring(0, tmp.indexOf(WSDL_STRING));
}

@WebEndpoint(name = "ServerPort")
private ServerIfc getServerPort() {
	ServerIfc port = super.getPort(new QName("network", "ServerPort"), ServerIfc.class);
	((BindingProvider) port).getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, path);
	return port;
}

public static ServerIfc newInstance(URL wsdlURL) {
	ClassLoader tccl = Thread.currentThread().getContextClassLoader();
	Thread.currentThread().setContextClassLoader(ServerService.class.getClassLoader());
	try {
		return new ServerService(wsdlURL).getServerPort();
	} finally {
		Thread.currentThread().setContextClassLoader(tccl);
	}
}
```

My bundle is ten times as large now, but everything works again.

**Comment by lukasj** [comment] 2020-05-18 14:13
@Melnorme1984 wrt "Embedded a bunch of dependencies in my bundle:"

depending on which JDK you are and what impl version you use:

- resolver is part of (some) JDKs, so necessary packages may be just reexported through some fragment (like it is [here](https://github.com/eclipse-ee4j/metro-wsit/blob/master/wsit/bundles/webservices-extra-jdk-packages/pom.xml#L36)) or just by using a system property (if your runtime supports it)

- gmbal - new versions of management-api and gmbal were published last week to help resolving some issues @col-panic pointed to, so with new [management-api](https://repo1.maven.org/maven2/org/glassfish/external/management-api/3.2.3/management-api-3.2.3.jar) and [gmbal-api-only](https://repo1.maven.org/maven2/org/glassfish/gmbal/gmbal-api-only/4.0.2/gmbal-api-only-4.0.2.jar), one can avoid having pfl* jars there; note that those new versions also contain module-infos.

**Comment by Melnorme1984** [comment] 2020-05-18 14:22
Yes, it seems my environment doesn't support multi-release JARs properly. As part of my experimentation, I was able to get around using `resolver` by manually modifying the JARs. But I'd rather keep things simple.

It looks like replacing `gmbal` with `gmbal-api-only` works, so that's good.

**Comment by brcolow** [comment] 2020-09-23 03:14
Something is wrong here.

I am using all latest dependencies:

```xml
        <dependency>
            <groupId>jakarta.jws</groupId>
            <artifactId>jakarta.jws-api</artifactId>
            <version>3.0.0-RC2</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>3.0.0-M4</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.ws</groupId>
            <artifactId>jakarta.xml.ws-api</artifactId>
            <version>3.0.0-RC3</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>3.0.0-RC3</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.ws</groupId>
            <artifactId>jaxws-rt</artifactId>
            <version>3.0.0-M4</version>
        </dependency>
```

I also am including a META-INF/services file named `jakarta.xml.ws.spi.Provider` with contents `com.sun.xml.ws.spi.ProviderImpl` but it is not being used. It is still going to the fallback which is failing. This is on Java 14.

I cannot add `provides jakarta.xml.ws.spi.Provider with com.sun.xml.ws.spi.ProviderImpl;` to `module-info.java` because that class is in `com.sun.xml` package.

Really unclear what to do here.

**Comment by elab** [comment] 2020-12-02 15:30
The thread pointed out by @Canos is really useful, especially (or exactly) if you switched from JDK8 to JDK11 (actually, any JDK9+) and running your app as JAR (as opposed to run in IDE): [Different classloaders in jdk8 and jdk11](https://github.com/spring-projects/spring-boot/issues/19427).

**Closed** 2021-02-20 13:36 UTC

**Comment by h908714124** [comment] 2021-02-22 10:47
I'm running into the same problem.
@lukasj you just closed this. Do I have to update some dependency now, and which one?

**Comment by lukasj** [comment] 2021-02-22 10:57
there is NO official build available yet. 

One option is to build snapshot from master. There is also 3.0.1 build available in [the staging repo](https://jakarta.oss.sonatype.org/#nexus-search;quick~jakarta.xml.ws-api) which needs testing and may be changed at any time without prior notice till it is fully tested, not only by TCK. If you want to use that, be warned that in case you use current build and the build in the staging repo changes, maven as such will NOT recognize new artifact and you will still be using the old build until you delete the copy from your local repo.

**Comment by h908714124** [comment] 2021-02-22 10:59
For the record, we're waiting for `3.0.1` release of `jakarta.jws:jakarta.jws-api` now?

**Comment by lukasj** [comment] 2021-02-22 11:04
no, `jakarta.jws:jakarta.jws-api` is the only dependency, which is not going to change for EE 9.1. There are about ~15 other projects which needs either to change or to adopt this change

**Comment by h908714124** [comment] 2021-02-22 11:07
Could you list these other projects, or link/create a tracker ticket, so people can see when the issue ("Provider com.sun.xml.internal.ws.spi.ProviderImpl not found") is resolved?

**Comment by lukasj** [comment] 2021-02-22 11:11
I'm really not good at doing paper work and I really don't want to spend time creating an issue for every change in every project I work on, that would be a nightmare and non-trivial amount of work given that is >20 repos/projects. All related projects are listed at https://github.com/eclipse-ee4j/metro-wsit/blob/master/etc/metro-dependencies.md Once everything is ready, new release on github appears.

**Comment by h908714124** [comment] 2021-02-22 11:14
Oh I see, thank you very much.

**Comment by vogella** [comment] 2021-05-06 13:47
I'm facing the same issue with a client. Is their an example setup somewhere available how to setup this for an OSGi environment? @col-panic you seem to have figure this out, coudl you share your setup?

**Comment by col-panic** [comment] 2021-05-06 14:26
@vogella not really. 

After the failed approaches documented here, we decided to keep the current release train on Java 8. 
Now we prepare for the upcoming development branch and will try to big bang Java 11. 

I am currently (what a coincidence) rebuilding the target in https://github.com/elexis/elexis-target and did your approach documented in http://blog.vogella.com/2021/03/08/eclipse-rcp-java-11-jaxb/ to fix JAXB (as opposed to mine with never release 2.4.0, there is another caveat documented in https://bugs.eclipse.org/bugs/show_bug.cgi?id=571532 however). Next step is JAXRS which is on my table for tomorrow next week.

If (When) I find a working approach I'll certainly share my setup!

**Comment by lukasj** [comment] 2021-05-06 15:13
do NOT use 2.4.0-XX versions, they are obsolete and will never (=in foreseeable future) be worked on. In reality, they are older than 2.3.2, likely even older. The latest versions for use, as of today, are 2.3.4 and 3.0.1

**Comment by h908714124** [comment] 2021-05-06 16:19
This closed issue seems to contain a lot of useful information.
Someone care to make a blog post or wiki page of it?

**Comment by col-panic** [comment] 2021-05-07 07:27
@vogella it seems like I already have it running - the step from a working JAXB in java 11 to JAX-RS does not seem to far. I manually package a feature (see https://github.com/elexis/elexis-target/blob/0ddde9cf23fa45d94b87fa278bef95cffb4ef28a/pom.xml#L102) which suffices to make a jax-rs client test running.

I saw a `java.lang.IllegalStateException: InjectionManagerFactory not found.` on first approach, which I could solve via https://stackoverflow.com/questions/44088493/jersey-stopped-working-with-injectionmanagerfactory-not-found (already integrated in the referenced pom.xml)

**Comment by vogella** [comment] 2021-05-07 09:19
@col-panic I'm trying to start a webservice in my OSGI runtime, not only a client. I found a way for the first issue via the Equinox Mailing list to work around the following error:

    Caused by: java.lang.ClassNotFoundException: com.sun.xml.ws.spi.ProviderImpl

This can be avoided by adding a fragment project to import the package for jakarta.xml.ws-api
````
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Ws-fragment
Bundle-SymbolicName: ws-fragment
Bundle-Version: 1.0.0.qualifier
Fragment-Host: jakarta.xml.ws-api;bundle-version="3.0.1"
Automatic-Module-Name: ws.fragment
Bundle-RequiredExecutionEnvironment: JavaSE-11
Import-Package: com.sun.xml.ws.spi;version="3.0.1"
````

Unfortunately this now results in a  jakarta.xml.soap.SOAPException which I'm currently investigating.

Caused by: jakarta.xml.soap.SOAPException: Unable to create SAAJ meta-factory: Provider com.sun.xml.internal.messaging.saaj.soap.SAAJMetaFactoryImpl not found
	at jakarta.xml.soap.SAAJMetaFactory.getInstance(SAAJMetaFactory.java:82)
	at jakarta.xml.soap.MessageFactory.newInstance(MessageFactory.java:120)
	at com.sun.xml.ws.api.SOAPVersion.<init>(SOAPVersion.java:162)
	... 43 more

I posted my work-in-progress here: https://github.com/vogellacompany/eclipsercp-javaws-java11 Suggestions or Pull request how to make this work are welcome.

**Comment by lukasj** [comment] 2021-05-07 09:24
@vogella implementation available is https://search.maven.org/artifact/com.sun.xml.messaging.saaj/saaj-impl/2.0.1/jar - you may need to get around the issue (should there be one) the same way you did with ws-fragment

**Comment by vogella** [comment] 2021-05-07 09:33
Thanks @lukasj. Looks like the package moved. 


![image](https://user-images.githubusercontent.com/139910/117429493-664f7200-af27-11eb-9288-a610ac51d4dd.png)


Can I instruct the system to look for com.sun.xml.messaging.saaj.soap.SAAJMetaFactoryImpl  instead of com.sun.xml.internal.messaging.saaj.soap.SAAJMetaFactoryImpl?

I tried creating a file /com.example.rcpclient/META-INF/services/javax.xml.soap.SAAJMetaFactory with the "com.sun.xml.messaging.saaj.soap.SAAJMetaFactoryImpl" as suggested in https://stackoverflow.com/questions/47199846/unable-to-create-saaj-meta-factory-after-packaging-as-jar but this did not work for me.

**Comment by lukasj** [comment] 2021-05-07 09:38
for [jax-ws](https://jakarta.ee/specifications/platform/9/apidocs/jakarta/xml/ws/spi/provider#provider--), system property is `jakarta.xml.ws.spi.Provider`
for [saaj](https://jakarta.ee/specifications/platform/9/apidocs/jakarta/xml/soap/saajmetafactory), system property is `jakarta.xml.soap.SAAJMetaFactory`

**Comment by vogella** [comment] 2021-05-07 10:27
Thanks @lukasj setting SAAJMetaFactory via the property allowed me to exchange the class. 
I had to add another fragment to give  jakarta.xml.soap-api access to the package com.sun.xml.messaging.saaj.soap;

The next error I get is:
````
Caused by: jakarta.xml.bind.JAXBException: return is not a valid property on class com.example.rcpclient.handlers.jaxws.SayHelloResponse
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getElementPropertyAccessor(JAXBContextImpl.java:908)
	at com.sun.xml.ws.db.glassfish.JAXBRIContextWrapper.getElementPropertyAccessor(JAXBRIContextWrapper.java:91)
	at com.sun.xml.ws.server.sei.EndpointResponseMessageBuilder$DocLit.<init>(EndpointResponseMessageBuilder.java:228)
	... 54 more
````

Which means that I have to configure JAXB for this project. I try this and update the ticket / Github repo is succesful.

**Comment by vogella** [comment] 2021-05-18 12:19
I added a JaxB provider and a fragment for this provider with the following fragment.

------------
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Binding
Bundle-SymbolicName: jaxb.impl.binding
Bundle-Version: 1.0.0.qualifier
Fragment-Host: jakarta.xml.bind-api;bundle-version="2.3.3"
Automatic-Module-Name: jaxb.impl.binding
Bundle-RequiredExecutionEnvironment: JavaSE-11
Import-Package: com.sun.xml.bind.v2;version="2.3.4"
-----------

Unfortunately this only leads to the next error: 


java.lang.InternalError: MASM0010: Unable to unmarshall metro config file from location [ bundleresource://87.fwk757340973/META-INF/jaxws-tubes-default.xml ]
	at com.sun.xml.ws.assembler.MetroConfigLoader.loadMetroConfig(MetroConfigLoader.java:234)
	at com.sun.xml.ws.assembler.MetroConfigLoader.init(MetroConfigLoader.java:117)
	at com.sun.xml.ws.assembler.MetroConfigLoader.<init>(MetroConfigLoader.java:91)
	at com.sun.xml.ws.assembler.TubelineAssemblyController.getTubeCreators(TubelineAssemblyController.java:93)
	at com.sun.xml.ws.assembler.MetroTubelineAssembler.createServer(MetroTubelineAssembler.java:146)
	at com.sun.xml.ws.server.WSEndpointImpl.<init>(WSEndpointImpl.java:163)
	at com.sun.xml.ws.server.EndpointFactory.create(EndpointFactory.java:307)
	at com.sun.xml.ws.server.EndpointFactory.create(EndpointFactory.java:302)
	at com.sun.xml.ws.server.EndpointFactory.createEndpoint(EndpointFactory.java:134)
	at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:578)
	at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:560)
	at com.sun.xml.ws.transport.http.server.EndpointImpl.createEndpoint(EndpointImpl.java:304)
	at com.sun.xml.ws.transport.http.server.EndpointImpl.publish(EndpointImpl.java:217)
	at com.sun.xml.ws.spi.ProviderImpl.createAndPublishEndpoint(ProviderImpl.java:111)
	at javax.xml.ws.Endpoint.publish(Endpoint.java:224)

Anyone had this error before and knows how to fix that? I tried coping the jaxws-tubes.xml
jaxws-tubes-default.xml files into the META-INF folder of my project but this is not used.

**Comment by vogella** [comment] 2021-05-18 13:20
I think that issue is discussed in https://github.com/eclipse-ee4j/metro-jax-ws/issues/128

**Comment by DhinguA** [comment] 2021-06-09 07:47
What combination of Jar do we need to use for JAX-WS Webservices? to avoid providerimpl internal package issue.
